// Generated by Wrangler by running `wrangler types types.d.ts`

interface Env {
  AI: any;
  STORAGE: R2Bucket;
  INPUT_QUEUE: Queue;
  PROCESSING_QUEUE: Queue;
  RESULTS_QUEUE: Queue;
}

interface R2Event {
  type: 'upload' | 'delete';
  key: string;
  size?: number;
  etag?: string;
  httpMetadata?: R2HTTPMetadata;
  customMetadata?: Record<string, string>;
}

type R2HTTPMetadata = Record<string, string>;
