name = 'llm-do'
main = 'src/index.ts'
compatibility_date = '2024-12-18'
compatibility_flags = ['nodejs_compat']

# Workers Logs
[observability]
enabled = true

# AI binding for model processing
[ai]
binding = 'AI'

# R2 bucket configuration
[[r2_buckets]]
binding = 'STORAGE'
bucket_name = 'llm-do'

# Enable event notifications for R2 bucket
[[r2_buckets.notifications]]
type = 'queue'
queue_name = 'llm-do-input'
event_types = ['upload']
filter = {prefix = 'input/', suffix = '.jsonl'}

# Queue configurations
[[queues.producers]]
binding = 'INPUT_QUEUE'
queue = 'llm-do-input'

[[queues.producers]]
binding = 'PROCESSING_QUEUE'
queue = 'llm-do-processing'

[[queues.producers]]
binding = 'RESULTS_QUEUE'
queue = 'llm-do-results'

[[queues.consumers]]
queue = 'llm-do-input'

[[queues.consumers]]
queue = 'llm-do-processing'

[[queues.consumers]]
queue = 'llm-do-results'
