name: Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
        env:
          NODE_ENV: test
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_WORKER_NAME: llm-do-test
          CLOUDFLARE_R2_BUCKET: llm-do-test-bucket
          CLOUDFLARE_QUEUE_NAME: llm-do-test-queue
          CLOUDFLARE_AI_MODEL: "@cf/meta/llama-2-7b-chat-int8"

      - name: Run load tests
        run: pnpm test:load
        env:
          NODE_ENV: test
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_WORKER_NAME: llm-do-test
          CLOUDFLARE_R2_BUCKET: llm-do-test-bucket
          CLOUDFLARE_QUEUE_NAME: llm-do-test-queue
          CLOUDFLARE_AI_MODEL: "@cf/meta/llama-2-7b-chat-int8"
